package apiv1

import (
	"context"
	"errors"
	"slices"
	"vc/internal/gen/registry/apiv1_registry"
	"vc/pkg/helpers"
	"vc/pkg/oauth2"
	"vc/pkg/openid4vci"

	"github.com/golang-jwt/jwt/v5"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
)

// OIDCCredentialOffer https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#name-credential-offer-endpoint
func (c *Client) OIDCCredentialOffer(ctx context.Context, req *openid4vci.CredentialOfferParameters) (*openid4vci.CredentialOfferParameters, error) {
	c.log.Debug("credential offer")
	return nil, nil
}

// OIDCNonce https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#name-nonce-endpoint
func (c *Client) OIDCNonce(ctx context.Context) (*openid4vci.NonceResponse, error) {
	nonce, err := openid4vci.GenerateNonce(0)
	if err != nil {
		return nil, err
	}
	response := &openid4vci.NonceResponse{
		CNonce: nonce,
	}
	return response, nil
}

// OIDCCredential makes a credential
//
//	@Summary		OIDCCredential
//	@ID				create-credential
//	@Description	Create credential endpoint
//	@Tags			dc4eu
//	@Accept			json
//	@Produce		json
//	@Success		200	{object}	apiv1_issuer.MakeSDJWTReply	"Success"
//	@Failure		400	{object}	helpers.ErrorResponse		"Bad Request"
//	@Param			req	body		openid4vci.CredentialRequest			true	" "
//	@Router			/credential [post]
func (c *Client) OIDCCredential(ctx context.Context, req *openid4vci.CredentialRequest) (*openid4vci.CredentialResponse, error) {
	c.log.Debug("credential", "req", req)

	dpop, err := oauth2.ValidateAndParseDPoPJWT(req.Headers.DPoP)
	if err != nil {
		c.log.Error(err, "failed to validate DPoP JWT")
		return nil, err
	}

	requestATH := req.Headers.HashAuthorizeToken()

	if !dpop.IsAccessTokenDPoP(requestATH) {
		return nil, errors.New("invalid DPoP token")

	}

	if slices.Contains(c.cfg.Common.SupportedPidVCT, req.VCT) {
		// pid flow
	} else {
		// non-pid flow
	}
	response := &openid4vci.CredentialResponse{
		Credential:      "eyJhbGciOiJFUzI1NiIsImtpZCI6ImRlZmF1bHRfc2lnbmluZ19rZXlfaWQiLCJ0eXAiOiJ2YytzZC1qd3QiLCJ2Y3RtIjpbImV5SjJZM1FpT2lKRWFYQnNiMjFoUTNKbFpHVnVkR2xoYkNJc0ltNWhiV1VpT2lKRWFYQnNiMjFoSUVOeVpXUmxiblJwWVd3aUxDSmtaWE5qY21sd2RHbHZiaUk2SWtWMWNtOXdaV0Z1SUV4bFlYSnVhVzVuSUUxdlpHVnNJRVJwY0d4dmJXRWdRM0psWkdWdWRHbGhiQzRpTENJa1kyOXRiV1Z1ZENJNklpSXNJbVJwYzNCc1lYa2lPbHQ3SW14aGJtY2lPaUpsYmkxVlV5SXNJbTVoYldVaU9pSkVhWEJzYjIxaElFTnlaV1JsYm5ScFlXd2lMQ0prWlhOamNtbHdkR2x2YmlJNklsQnZjblJoWW14bElFVjFjbTl3WldGdUlFeGxZWEp1YVc1bklFMXZaR1ZzSUNoRlRFMHBJRVJwY0d4dmJXRWdRM0psWkdWdWRHbGhiQzRpTENKeVpXNWtaWEpwYm1jaU9uc2ljMmx0Y0d4bElqcDdJbXh2WjI4aU9uc2lkWEpwSWpvaUlpd2lkWEpwSTJsdWRHVm5jbWwwZVNJNklpSXNJbUZzZEY5MFpYaDBJam9pSW4wc0ltSmhZMnRuY205MWJtUmZZMjlzYjNJaU9pSWlMQ0owWlhoMFgyTnZiRzl5SWpvaUluMHNJbk4yWjE5MFpXMXdiR0YwWlhNaU9sdDdJblZ5YVNJNkltaDBkSEJ6T2k4dmNtRjNMbWRwZEdoMVluVnpaWEpqYjI1MFpXNTBMbU52YlM5a1l6UmxkUzkyWXk4Mk16TTVOREJpTUdJd01HRmlNalU1WVdZd01XTm1ZbVptT1RVNFpqRm1abVZpWmpVeE56WmhMMmx0WVdkbGN5OWthWEJzYjIxaFZHVnRjR3hoZEdVdWMzWm5JaXdpZFhKcEkybHVkR1ZuY21sMGVTSTZJbk5vWVRJMU5pMHhZV05rTkRnNE16Z3lObUZpWVRBek1UaGtNakU1TWpFelltSTNOV0U1Wkdaak9EVTRaamt5Tm1VNU0yWTFOell5TWpRME1USXpNREZtWlRNd01UaGhJaXdpY0hKdmNHVnlkR2xsY3lJNmV5SnZjbWxsYm5SaGRHbHZiaUk2SWlJc0ltTnZiRzl5WDNOamFHVnRaU0k2SWlJc0ltTnZiblJ5WVhOMElqb2lJbjE5WFgxOVhTd2lZMnhoYVcxeklqcGJYU3dpYzJOb1pXMWhYM1Z5YkNJNklpSXNJbk5qYUdWdFlWOTFjbXdqYVc1MFpXZHlhWFI1SWpvaUlpd2laWGgwWlc1a2N5STZJaUlzSW1WNGRHVnVaSE1qYVc1MFpXZHlhWFI1SWpvaUluMD0iXX0.eyJAY29udGV4dCI6WyJodHRwczovL3d3dy53My5vcmcvMjAxOC9jcmVkZW50aWFscy92MSIsImh0dHA6Ly9kYXRhLmV1cm9wYS5ldS9zbmIvbW9kZWwvY29udGV4dC9lZGMtYXAiXSwiX3NkX2FsZyI6InNoYS0yNTYiLCJjbmYiOnsiandrIjp7ImtpZCI6Ik0zRjJkQzEzVWtoTmEyMVZXbGREVkZaUVJXZGZXVkZoVEhoQ2RteEhTV3h0VGtwYWJuRlliWFptTkEiLCJjcnYiOiJQLTI1NiIsImt0eSI6IkVDIiwieCI6ImFDRjQtU1hlS1BMNmtoRlZiSFZOX2xRZHFCTGNMQmtoR1NDcGJ0R2RvRTQiLCJ5IjoieTd2b1EyNUtyd3RZV0hqRnZFUEw5em8wN1UtMDZVM3pZQTh4LTBvbHcxSSJ9fSwiY3JlZGVudGlhbFByb2ZpbGVzIjp7ImlkIjoiaHR0cDovL2RhdGEuZXVyb3BhLmV1L3NuYi9jcmVkZW50aWFsL2UzNDkyOTAzNWIiLCJpblNjaGVtZSI6eyJpZCI6Imh0dHA6Ly9kYXRhLmV1cm9wYS5ldS9zbmIvY3JlZGVudGlhbC8yNTgzMWMyIiwidHlwZSI6IkNvbmNlcHRTY2hlbWUifSwicHJlZkxhYmVsIjp7ImVuIjoiR2VuZXJpYyJ9LCJ0eXBlIjoiQ29uY2VwdCJ9LCJjcmVkZW50aWFsU2NoZW1hIjp7ImlkIjoiaHR0cDovL2RhdGEuZXVyb3BhLmV1L3NuYi9tb2RlbC9hcC9lZGMtZ2VuZXJpYy1mdWxsIiwidHlwZSI6IlNoYWNsVmFsaWRhdG9yMjAxNyJ9LCJjcmVkZW50aWFsU3ViamVjdCI6eyJkYXRlT2ZCaXJ0aCI6IjE5NzItMDYtMTlUMDA6MDA6MDAiLCJmYW1pbHlOYW1lIjp7InVuZCI6IkJvcyBBYW52cmFnZXJvdWRlciJ9LCJnaXZlbk5hbWUiOnsidW5kIjoiQ2NjYyBPdWRlcnR3ZWUifSwiaGFzQ2xhaW0iOnsiYXdhcmRlZEJ5Ijp7ImF3YXJkaW5nQm9keSI6eyJob21lcGFnZSI6eyJjb250ZW50VVJMIjoiaHR0cHM6Ly9kdW8ubmwiLCJpZCI6InVybjplcGFzczp3ZWJSZXNvdXJjZToxYjRlNmE4Yy1hMzYyLTQwYmMtOWM2My0xODg5YjM3NWNkZjAiLCJ0eXBlIjoiV2ViUmVzb3VyY2UifSwiaWQiOiJ1cm46ZXBhc3M6b3JnOjA2OWJiMjcyLWIwYjQtNGJmMC1iZTI1LTA2M2UxODExODQ1NSIsImlkZW50aWZpZXIiOlt7ImlkIjoidXJuOmVwYXNzOmlkZW50aWZpZXI6ZWRkYzY1ZTktMWUzZS00ZmY4LThlYWMtYTNiMWFmMjg3OGQ2Iiwibm90YXRpb24iOiJkdW8ubmwiLCJzY2hlbWVOYW1lIjoic2NoYWMiLCJ0eXBlIjoiSWRlbnRpZmllciJ9LHsiaWQiOiJ1cm46ZXBhc3M6aWRlbnRpZmllcjowYmNmMmFmNS1jYTU0LTQ0OTAtOTcxYy0zMWU5OTAyYzMxNGYiLCJub3RhdGlvbiI6IjI3TkYiLCJzY2hlbWVOYW1lIjoiQlJJTiIsInR5cGUiOiJJZGVudGlmaWVyIn1dLCJsZWdhbE5hbWUiOnsibmwiOiJBcnRFWiJ9LCJsb2NhdGlvbiI6eyJhZGRyZXNzIjp7ImNvdW50cnlDb2RlIjp7ImlkIjoiaHR0cDovL3B1YmxpY2F0aW9ucy5ldXJvcGEuZXUvcmVzb3VyY2UvYXV0aG9yaXR5L2NvdW50cnkvTkxEIiwiaW5TY2hlbWUiOnsiaWQiOiJodHRwOi8vcHVibGljYXRpb25zLmV1cm9wYS5ldS9yZXNvdXJjZS9hdXRob3JpdHkvY291bnRyeSIsInR5cGUiOiJDb25jZXB0U2NoZW1lIn0sIm5vdGF0aW9uIjoiY291bnRyeSIsInByZWZMYWJlbCI6eyJlbiI6Ik5ldGhlcmxhbmRzIn0sInR5cGUiOiJDb25jZXB0In0sImlkIjoidXJuOmVwYXNzOmFkZHJlc3M6NTNhYzVlNjQtOGJhMi00ZmEyLThhYmItZTFlZjlhMTU2MmQ5IiwidHlwZSI6IkFkZHJlc3MifSwiaWQiOiJ1cm46ZXBhc3M6bG9jYXRpb246ZmJjNTYwNDctNjg2OS00YTgxLWExNGMtZDZlMWQzYWZjNDNjIiwidHlwZSI6IkxvY2F0aW9uIn0sInR5cGUiOiJPcmdhbmlzYXRpb24ifSwiYXdhcmRpbmdEYXRlIjoiMjAwNC0wMy0zMVQwMDowMDowMCIsImlkIjoidXJuOmVwYXNzOmF3YXJkaW5nUHJvY2VzczowMzE3YzkyMi0xMDQ0LTQ1NWYtODE1Ny1kZjRlODUzNzNhNmIiLCJ0eXBlIjoiQXdhcmRpbmdQcm9jZXNzIiwidXNlZCI6eyJhc3Nlc3NlZEJ5Ijp7ImhvbWVwYWdlIjp7ImNvbnRlbnRVUkwiOiJodHRwczovL2R1by5ubCIsImlkIjoidXJuOmVwYXNzOndlYlJlc291cmNlOjIzZDE0MTQzLTIwN2ItNDgzNC04N2Y1LTdiODU2OGI4MjQ4ZiIsInR5cGUiOiJXZWJSZXNvdXJjZSJ9LCJpZCI6InVybjplcGFzczpvcmc6OTlhMDdkMzYtYWU3Yy00OTM1LWJlYTYtOGZlMTIyYjIzMDdkIiwiaWRlbnRpZmllciI6W3siaWQiOiJ1cm46ZXBhc3M6aWRlbnRpZmllcjoyY2JmYTMxNy1mNjY1LTQxMDctYjJkYy01OTQ5NjMyZmYzODgiLCJub3RhdGlvbiI6ImR1by5ubCIsInNjaGVtZU5hbWUiOiJzY2hhYyIsInR5cGUiOiJJZGVudGlmaWVyIn0seyJpZCI6InVybjplcGFzczppZGVudGlmaWVyOmI5OTNhMzhmLTJiMmEtNGYwNS1iYzQ5LTgxMzJhYWM5N2Y3MSIsIm5vdGF0aW9uIjoiMjdORiIsInNjaGVtZU5hbWUiOiJCUklOIiwidHlwZSI6IklkZW50aWZpZXIifV0sImxlZ2FsTmFtZSI6eyJubCI6IkFydEVaIn0sImxvY2F0aW9uIjp7ImFkZHJlc3MiOnsiY291bnRyeUNvZGUiOnsiaWQiOiJodHRwOi8vcHVibGljYXRpb25zLmV1cm9wYS5ldS9yZXNvdXJjZS9hdXRob3JpdHkvY291bnRyeS9OTEQiLCJpblNjaGVtZSI6eyJpZCI6Imh0dHA6Ly9wdWJsaWNhdGlvbnMuZXVyb3BhLmV1L3Jlc291cmNlL2F1dGhvcml0eS9jb3VudHJ5IiwidHlwZSI6IkNvbmNlcHRTY2hlbWUifSwibm90YXRpb24iOiJjb3VudHJ5IiwicHJlZkxhYmVsIjp7ImVuIjoiTmV0aGVybGFuZHMifSwidHlwZSI6IkNvbmNlcHQifSwiaWQiOiJ1cm46ZXBhc3M6YWRkcmVzczo0MDMzNmIxZS1lOThlLTRhZDQtYjg1Mi1mNDIwMTYwMjkwZTQiLCJ0eXBlIjoiQWRkcmVzcyJ9LCJpZCI6InVybjplcGFzczpsb2NhdGlvbjpjMDcxNjIyOC1jZGI3LTRkODEtOGY5MS0yM2M1ZDY3NWE5MDEiLCJ0eXBlIjoiTG9jYXRpb24ifSwidHlwZSI6Ik9yZ2FuaXNhdGlvbiJ9LCJhd2FyZGVkQnkiOnsiYXdhcmRpbmdCb2R5Ijp7ImhvbWVwYWdlIjp7ImNvbnRlbnRVUkwiOiJodHRwczovL2R1by5ubCIsImlkIjoidXJuOmVwYXNzOndlYlJlc291cmNlOjJhZjczN2M2LTAwNjEtNDc4YS1iMWU4LWMwMzdhMDJhM2UwOCIsInR5cGUiOiJXZWJSZXNvdXJjZSJ9LCJpZCI6InVybjplcGFzczpvcmc6ZDI1NTA4ZDAtZDE1Yi00ZjdlLTkwZDgtY2U3Njk4NDJiNDk3IiwiaWRlbnRpZmllciI6W3siaWQiOiJ1cm46ZXBhc3M6aWRlbnRpZmllcjo0ZTRlYzBjNi0yOGViLTQ3MzAtOTM3OC0xZDQzZjAzMzUzMDIiLCJub3RhdGlvbiI6ImR1by5ubCIsInNjaGVtZU5hbWUiOiJzY2hhYyIsInR5cGUiOiJJZGVudGlmaWVyIn0seyJpZCI6InVybjplcGFzczppZGVudGlmaWVyOjI1YThlZjIxLWE2MzQtNGFmMy1hZjZmLTQ2ZjFhOTU4OGNmNiIsIm5vdGF0aW9uIjoiMjdORiIsInNjaGVtZU5hbWUiOiJCUklOIiwidHlwZSI6IklkZW50aWZpZXIifV0sImxlZ2FsTmFtZSI6eyJubCI6IkFydEVaIn0sImxvY2F0aW9uIjp7ImFkZHJlc3MiOnsiY291bnRyeUNvZGUiOnsiaWQiOiJodHRwOi8vcHVibGljYXRpb25zLmV1cm9wYS5ldS9yZXNvdXJjZS9hdXRob3JpdHkvY291bnRyeS9OTEQiLCJpblNjaGVtZSI6eyJpZCI6Imh0dHA6Ly9wdWJsaWNhdGlvbnMuZXVyb3BhLmV1L3Jlc291cmNlL2F1dGhvcml0eS9jb3VudHJ5IiwidHlwZSI6IkNvbmNlcHRTY2hlbWUifSwibm90YXRpb24iOiJjb3VudHJ5IiwicHJlZkxhYmVsIjp7ImVuIjoiTmV0aGVybGFuZHMifSwidHlwZSI6IkNvbmNlcHQifSwiaWQiOiJ1cm46ZXBhc3M6YWRkcmVzczoyNzBjNzdhMC01MmI4LTQyYTctOTFkMy0zOGZjNTZmYzNlODMiLCJ0eXBlIjoiQWRkcmVzcyJ9LCJpZCI6InVybjplcGFzczpsb2NhdGlvbjplNGE2ZWU1OS0yMzY4LTRiZWUtYmFjNi1lZGNiOWU4MmJmNjAiLCJ0eXBlIjoiTG9jYXRpb24ifSwidHlwZSI6Ik9yZ2FuaXNhdGlvbiJ9LCJhd2FyZGluZ0RhdGUiOiIyMDA0LTAzLTMxVDAwOjAwOjAwIiwiaWQiOiJ1cm46ZXBhc3M6YXdhcmRpbmdQcm9jZXNzOjBhYzliZjY1LWViZjktNDQ4ZS04YjE4LWM5M2Q0ZjdkNDViNSIsInR5cGUiOiJBd2FyZGluZ1Byb2Nlc3MifSwiZGF0ZUlzc3VlZCI6IjIwMDQtMDMtMzFUMDA6MDA6MDAiLCJkZXNjcmlwdGlvbiI6eyJubCI6IkhCTyBNYXN0ZXIgQXJjaGl0ZWN0dXVyIn0sImdyYWRlIjp7ImlkIjoidXJuOmVwYXNzOm5vdGU6ZmU1MGVjYjMtOTllZC00M2Y3LTg3ZDktYjM5YjE5MjNhYWUxIiwibm90ZUZvcm1hdCI6eyJkZWZpbml0aW9uIjp7InVuZCI6Imh0dHA6Ly9kYXRhLmV1cm9wYS5ldS9zbmIvbW9kZWwvZWxtL25vdGVGb3JtYXQifSwiaWQiOiJ1cm46ZXBhc3M6Y29uY2VwdDo1NjU1NTU4NC0yZTJiLTQ0OTQtYmZlMy0zNDY3MDgwZGZhZTMiLCJub3RhdGlvbiI6InRleHQvcGxhaW4iLCJ0eXBlIjoiQ29uY2VwdCJ9LCJub3RlTGl0ZXJhbCI6eyJ1bmQiOiJwYXNzZWQifSwidHlwZSI6Ik5vdGUifSwiZ3JhZGVTdGF0dXMiOnsiaWQiOiJodHRwOi8vZGF0YS5ldXJvcGEuZXUvc25iL2dyYWRlLXN0YXR1cy9jXzYwYTFjZjlhIiwiaW5TY2hlbWUiOnsiaWQiOiJodHRwOi8vZGF0YS5ldXJvcGEuZXUvc25iL2dyYWRlLXN0YXR1cy8yNTgzMWMyIiwidHlwZSI6IkNvbmNlcHRTY2hlbWUifSwibm90YXRpb24iOiJncmFkZS1zdGF0dXMiLCJwcmVmTGFiZWwiOnsiZW4iOiJwYXNzIn0sInR5cGUiOiJDb25jZXB0In0sImlkIjoiY29udmVydGVyOmFzc2Vzc21lbnQ6MSIsImlkZW50aWZpZXIiOlt7ImlkIjoidXJuOmVwYXNzOmlkZW50aWZpZXI6ZDU1MjY4MjQtNzhlMi00Mzk3LWI0MzYtYTdkNTI4NTJhMTZkIiwibm90YXRpb24iOiI0NDMzNiIsInNjaGVtZU5hbWUiOiJJU0FUIiwidHlwZSI6IklkZW50aWZpZXIifSx7ImlkIjoidXJuOmVwYXNzOmlkZW50aWZpZXI6OWJhOGFlYTUtYjFmNC00YzIzLTlhYjAtY2EwMzFmZTJlYjY0Iiwibm90YXRpb24iOiJEZWdyZWUgUHJvZ3JhbW1lIiwic2NoZW1lTmFtZSI6ImVsbW86dHlwZTpsb3MiLCJ0eXBlIjoiSWRlbnRpZmllciJ9XSwic3BlY2lmaWVkQnkiOnsiaWQiOiJ1cm46ZXBhc3M6bGVhcm5pbmdBc3Nlc3NtZW50U3BlYzowNjcwZWE0MS0xNTY0LTRjYmYtODI0Yy0xYzk3ZjBhZTg4NzYiLCJ0aXRsZSI6eyJubCI6IkhCTyBNYXN0ZXIgQXJjaGl0ZWN0dXVyIn0sInR5cGUiOiJMZWFybmluZ0Fzc2Vzc21lbnRTcGVjaWZpY2F0aW9uIn0sInRpdGxlIjp7Im5sIjoiSEJPIE1hc3RlciBBcmNoaXRlY3R1dXIifSwidHlwZSI6IkxlYXJuaW5nQXNzZXNzbWVudCJ9fSwiZGVzY3JpcHRpb24iOnsibmwiOiJIQk8gTWFzdGVyIEFyY2hpdGVjdHV1ciJ9LCJpZCI6InVybjplcGFzczpsZWFybmluZ0FjaGlldmVtZW50Ojk5YmE1NzA5LTMxNzQtNDc3NS05ODQ1LWQxZTM5ODI0NjgyMiIsImlkZW50aWZpZXIiOlt7ImlkIjoidXJuOmVwYXNzOmlkZW50aWZpZXI6ZWQ5NDhiYmItY2FjNi00MzU3LWEzMjktYzUzYzZmOTM2OWEzIiwibm90YXRpb24iOiI0NDMzNiIsInNjaGVtZU5hbWUiOiJJU0FUIiwidHlwZSI6IklkZW50aWZpZXIifSx7ImlkIjoidXJuOmVwYXNzOmlkZW50aWZpZXI6OWEyZjBjOGUtMTRkMy00NWRlLWIzMzYtNTJlZjUwZjhhMmI1Iiwibm90YXRpb24iOiJEZWdyZWUgUHJvZ3JhbW1lIiwic2NoZW1lTmFtZSI6ImVsbW86dHlwZTpsb3MiLCJ0eXBlIjoiSWRlbnRpZmllciJ9XSwic3BlY2lmaWVkQnkiOnsiZWR1Y2F0aW9uTGV2ZWwiOnsiaWQiOiJodHRwOi8vZGF0YS5ldXJvcGEuZXUvc25iL2VxZi83IiwiaW5TY2hlbWUiOnsiaWQiOiJodHRwOi8vZGF0YS5ldXJvcGEuZXUvc25iL2VxZi8yNTgzMWMyIiwidHlwZSI6IkNvbmNlcHRTY2hlbWUifSwibm90YXRpb24iOiJlcWYtbGV2ZWwiLCJwcmVmTGFiZWwiOnsiZW4iOiJMZXZlbCA3In0sInR5cGUiOiJDb25jZXB0In0sImVxZkxldmVsIjp7ImlkIjoiaHR0cDovL2RhdGEuZXVyb3BhLmV1L3NuYi9lcWYvNyIsImluU2NoZW1lIjp7ImlkIjoiaHR0cDovL2RhdGEuZXVyb3BhLmV1L3NuYi9lcWYvMjU4MzFjMiIsInR5cGUiOiJDb25jZXB0U2NoZW1lIn0sIm5vdGF0aW9uIjoiZXFmLWxldmVsIiwicHJlZkxhYmVsIjp7ImVuIjoiTGV2ZWwgNyJ9LCJ0eXBlIjoiQ29uY2VwdCJ9LCJpZCI6InVybjplcGFzczpxdWFsaWZpY2F0aW9uOjlmYzczZTA0LTQzZWItNDY0Mi05OWUzLTk4YTBiZDg3OGQwNyIsInRpdGxlIjp7Im5sIjoiSEJPIE1hc3RlciBBcmNoaXRlY3R1dXIifSwidHlwZSI6IlF1YWxpZmljYXRpb24ifSwidGl0bGUiOnsibmwiOiJIQk8gTWFzdGVyIEFyY2hpdGVjdHV1ciJ9LCJ0eXBlIjoiTGVhcm5pbmdBY2hpZXZlbWVudCJ9LCJpZCI6InVybjplcGFzczpwZXJzb246MTMzNWJmYTUtM2Q4Zi00MDVjLThlYjMtOTU4ZTFiZWNlYThjIiwidHlwZSI6IlBlcnNvbiJ9LCJkaXNwbGF5UGFyYW1ldGVyIjp7ImlkIjoidXJuOmVwYXNzOmRpc3BsYXlQYXJhbWV0ZXI6MSIsImluZGl2aWR1YWxEaXNwbGF5Ijp7ImRpc3BsYXlEZXRhaWwiOnsiaWQiOiJ1cm46ZXBhc3M6ZGlzcGxheURldGFpbDpjYmI5NjVjNy1hNzFiLTQ2NGUtODY1Yi1mYWYyMTMwZTQwZDQiLCJpbWFnZSI6eyJjb250ZW50IjoiLzlqLzJ3QkRBQU1DQWdJQ0FnTUNBZ0lEQXdNREJBWUVCQVFFQkFnR0JnVUdDUWdLQ2drSUNRa0tEQThNQ2dzT0N3a0pEUkVORGc4UUVCRVFDZ3dTRXhJUUV3OFFFQkQveVFBTENBQUJBQUVCQVJFQS84d0FCZ0FRRUFYLzJnQUlBUUVBQUQ4QTBzOGcvOWs9IiwiY29udGVudEVuY29kaW5nIjp7ImlkIjoiaHR0cDovL2RhdGEuZXVyb3BhLmV1L3NuYi9lbmNvZGluZy82MTQ2Y2RlN2RkIiwiaW5TY2hlbWUiOnsiaWQiOiJodHRwOi8vZGF0YS5ldXJvcGEuZXUvc25iL2VuY29kaW5nLzI1ODMxYzIiLCJ0eXBlIjoiQ29uY2VwdFNjaGVtZSJ9LCJwcmVmTGFiZWwiOnsiZW4iOiJiYXNlNjQifSwidHlwZSI6IkNvbmNlcHQifSwiY29udGVudFR5cGUiOnsiaWQiOiJodHRwOi8vcHVibGljYXRpb25zLmV1cm9wYS5ldS9yZXNvdXJjZS9hdXRob3JpdHkvZmlsZS10eXBlL0pQRUciLCJpblNjaGVtZSI6eyJpZCI6Imh0dHA6Ly9wdWJsaWNhdGlvbnMuZXVyb3BhLmV1L3Jlc291cmNlL2F1dGhvcml0eS9maWxlLXR5cGUiLCJ0eXBlIjoiQ29uY2VwdFNjaGVtZSJ9LCJub3RhdGlvbiI6ImZpbGUtdHlwZSIsInByZWZMYWJlbCI6eyJlbiI6IkpQRUcifSwidHlwZSI6IkNvbmNlcHQifSwiaWQiOiJ1cm46ZXBhc3M6bWVkaWFPYmplY3Q6MWI1ZTI3MTEtODFmNS00NWUwLWE3N2YtM2MwYzQ3ZDYwOTE4IiwidHlwZSI6Ik1lZGlhT2JqZWN0In0sInBhZ2UiOjEsInR5cGUiOiJEaXNwbGF5RGV0YWlsIn0sImlkIjoidXJuOmVwYXNzOmluZGl2aWR1YWxEaXNwbGF5OmEwYTNkODA4LTk2ZDYtNGI5Ny05NWU2LTI1NmFiZjk0OGZmMSIsImxhbmd1YWdlIjp7ImlkIjoiaHR0cDovL3B1YmxpY2F0aW9ucy5ldXJvcGEuZXUvcmVzb3VyY2UvYXV0aG9yaXR5L2xhbmd1YWdlL0VORyIsImluU2NoZW1lIjp7ImlkIjoiaHR0cDovL3B1YmxpY2F0aW9ucy5ldXJvcGEuZXUvcmVzb3VyY2UvYXV0aG9yaXR5L2xhbmd1YWdlIiwidHlwZSI6IkNvbmNlcHRTY2hlbWUifSwibm90YXRpb24iOiJsYW5ndWdhZ2UiLCJwcmVmTGFiZWwiOnsiZW4iOiJlbiJ9LCJ0eXBlIjoiQ29uY2VwdCJ9LCJ0eXBlIjoiSW5kaXZpZHVhbERpc3BsYXkifSwibGFuZ3VhZ2UiOnsiaWQiOiJodHRwOi8vcHVibGljYXRpb25zLmV1cm9wYS5ldS9yZXNvdXJjZS9hdXRob3JpdHkvbGFuZ3VhZ2UvRU5HIiwiaW5TY2hlbWUiOnsiaWQiOiJodHRwOi8vcHVibGljYXRpb25zLmV1cm9wYS5ldS9yZXNvdXJjZS9hdXRob3JpdHkvbGFuZ3VhZ2UiLCJ0eXBlIjoiQ29uY2VwdFNjaGVtZSJ9LCJub3RhdGlvbiI6Imxhbmd1Z2FnZSIsInByZWZMYWJlbCI6eyJlbiI6ImVuIn0sInR5cGUiOiJDb25jZXB0In0sInByaW1hcnlMYW5ndWFnZSI6eyJpZCI6Imh0dHA6Ly9wdWJsaWNhdGlvbnMuZXVyb3BhLmV1L3Jlc291cmNlL2F1dGhvcml0eS9sYW5ndWFnZS9FTkciLCJpblNjaGVtZSI6eyJpZCI6Imh0dHA6Ly9wdWJsaWNhdGlvbnMuZXVyb3BhLmV1L3Jlc291cmNlL2F1dGhvcml0eS9sYW5ndWFnZSIsInR5cGUiOiJDb25jZXB0U2NoZW1lIn0sIm5vdGF0aW9uIjoibGFuZ3VnYWdlIiwicHJlZkxhYmVsIjp7ImVuIjoiZW4ifSwidHlwZSI6IkNvbmNlcHQifSwidGl0bGUiOnsiZW4iOiJBIGNvbnZlcnRlZCBkb2N1bWVudCBmcm9tIEVMTU86MS43In0sInR5cGUiOiJEaXNwbGF5UGFyYW1ldGVyIn0sImV4cCI6MTc4MDQ4MDY2MywiaXNzIjoiaHR0cHM6Ly92Yy1pbnRlcm9wLTMuc3VuZXQuc2UiLCJpc3N1YW5jZURhdGUiOiIyMDI1LTAzLTI1VDA3OjUyOjM4IiwiaXNzdWVkIjoiMjAyNS0wMy0yNVQwNzo1MjozOCIsIm5iZiI6MTc0ODk0NDY2MywidHlwZSI6WyJWZXJpZmlhYmxlQ3JlZGVudGlhbCIsIkV1cm9wZWFuRGlnaXRhbENyZWRlbnRpYWwiXSwidmFsaWRGcm9tIjoiMjAyNS0wMy0yNVQwNzo1MjozOCIsInZjdCI6InVybjplZHVpOmRpcGxvbWE6MSJ9.LjeOPoP0FFqZnZBbypSxM5NUoy_O0Khpidd2Qj4vyQLWDUjuv_CQ-jwQoQjUT-cTWU0hnTxd7JYQgPlGxX__-A~",
		TransactionID:   "",
		CNonce:          "",
		CNonceExpiresIn: 0,
		NotificationID:  "",
	}

	return response, nil
}

// OIDCDeferredCredential https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#name-deferred-credential-endpoin
func (c *Client) OIDCDeferredCredential(ctx context.Context, req *openid4vci.DeferredCredentialRequest) (*openid4vci.CredentialResponse, error) {
	c.log.Debug("deferred credential", "req", req)
	// run the same code as OIDCCredential
	return nil, nil
}

// OIDCredentialOfferURI https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0-14.html#name-sending-credential-offer-by-
func (c *Client) OIDCredentialOfferURI(ctx context.Context, req *openid4vci.CredentialOfferURIRequest) (*openid4vci.CredentialOfferParameters, error) {
	c.log.Debug("credential offer uri", "req", req.CredentialOfferUUID)
	doc, err := c.db.VCCredentialOfferColl.Get(ctx, req.CredentialOfferUUID)
	if err != nil {
		c.log.Debug("failed to marshal document data", "error", err)
		return nil, err
	}

	return &doc.CredentialOfferParameters, nil
}

// OIDCNotification https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#name-notification-endpoint
func (c *Client) OIDCNotification(ctx context.Context, req *openid4vci.NotificationRequest) error {
	c.log.Debug("notification", "req", req)
	return nil
}

// OIDCMetadata https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0-ID1.html#name-credential-issuer-metadata-
func (c *Client) OIDCMetadata(ctx context.Context) (*openid4vci.CredentialIssuerMetadataParameters, error) {
	c.log.Debug("metadata request")

	signedMetadata, err := c.issuerMetadata.Sign(jwt.SigningMethodRS256, c.issuerMetadataSigningKey, c.issuerMetadataSigningChain)
	if err != nil {
		return nil, err
	}
	if err := helpers.Check(ctx, c.cfg, signedMetadata, c.log); err != nil {
		c.log.Error(err, "failed to check metadata")
		return nil, err
	}

	return signedMetadata, nil
}

// RevokeRequest is the request for GenericRevoke
type RevokeRequest struct {
	AuthenticSource string `json:"authentic_source"`
	DocumentType    string `json:"document_type"`
	DocumentID      string `json:"document_id"`
	RevocationID    string `json:"revocation_id"`
}

// RevokeReply is the reply for GenericRevoke
type RevokeReply struct {
	Data struct {
		Status bool `json:"status"`
	}
}

// Revoke revokes a document
//
//	@Summary		Revoke
//	@ID				generic-revoke
//	@Description	Revoke endpoint
//	@Tags			dc4eu
//	@Accept			json
//	@Produce		json
//	@Success		200	{object}	RevokeReply				"Success"
//	@Failure		400	{object}	helpers.ErrorResponse	"Bad Request"
//	@Param			req	body		RevokeRequest			true	" "
//	@Router			/revoke [post]
func (c *Client) Revoke(ctx context.Context, req *RevokeRequest) (*RevokeReply, error) {
	optInsecure := grpc.WithTransportCredentials(insecure.NewCredentials())

	conn, err := grpc.NewClient(c.cfg.Registry.GRPCServer.Addr, optInsecure)
	if err != nil {
		return nil, err
	}
	defer conn.Close()

	client := apiv1_registry.NewRegistryServiceClient(conn)
	resp, err := client.Revoke(ctx, &apiv1_registry.RevokeRequest{
		Entity: "mura",
	})
	if err != nil {
		return nil, err
	}

	reply := &RevokeReply{
		Data: struct {
			Status bool `json:"status"`
		}{
			Status: resp.Status,
		},
	}
	return reply, nil
}
